In [1]:
import sys
sys.path.append("..")
%cd ..

/Users/AsgerSturisTang/OneDrive - Danmarks Tekniske Universitet/DTU/6. Semester/Bachelor2021


In [320]:
from DataPrep.ImportData import importer
from Modelling import modelling
import keras
from keras import Sequential
from keras.layers import Dense, LSTM, Dropout
import pyforest
import torch



In [22]:
m = modelling()
df = m.df.drop(columns=["Start Date"])

In [313]:
X_train,X_test, X_val,y_train,y_test, y_val = m.ttsplit(df)

In [74]:
labels = df.Label.unique()

In [316]:
stackings_X_test = []
stackings_X_train = []
stackings_X_val = []
stackings_y_test = []
stackings_y_train = []
stackings_y_val = []
for l in labels:
    stackings_X_test.append(tf.transpose(tf.ragged.constant(X_test[X_test.Label == l])))
    stackings_y_test.append(tf.transpose(tf.ragged.constant(y_test[X_test.Label == l])))
    stackings_X_train.append(tf.transpose(tf.ragged.constant(X_train[X_train.Label == l])))
    stackings_y_train.append(tf.transpose(tf.ragged.constant(y_train[X_train.Label == l])))
    stackings_X_val.append(tf.transpose(tf.ragged.constant(X_val[X_val.Label == l])))
    stackings_y_val.append(tf.transpose(tf.ragged.constant(y_val[X_val.Label == l])))


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [312]:
stackings_y

[<tf.Tensor: shape=(3076,), dtype=float64, numpy=
 array([1.56236425, 1.72684093, 2.32557269, ..., 2.58604348, 3.51912121,
        3.44192895])>,
 <tf.Tensor: shape=(2975,), dtype=float64, numpy=
 array([1.79773867, 2.126648  , 1.64598567, ..., 2.48196653, 3.71289299,
        3.81953125])>,
 <tf.Tensor: shape=(2992,), dtype=float64, numpy=
 array([1.6764479 , 2.23289617, 2.002042  , ..., 2.5581    , 2.70141744,
        2.62326973])>,
 <tf.Tensor: shape=(1919,), dtype=float64, numpy=
 array([0.14002725, 3.585802  , 2.84041792, ..., 5.01466667, 4.44631579,
        5.48564706])>,
 <tf.Tensor: shape=(1824,), dtype=float64, numpy=
 array([2.032795  , 2.10030061, 2.80736562, ..., 3.61629966, 3.62494058,
        2.321     ])>,
 <tf.Tensor: shape=(1617,), dtype=float64, numpy=
 array([2.04522226, 2.98106305, 2.40879814, ..., 1.77025686, 3.45274227,
        3.59354989])>,
 <tf.Tensor: shape=(1442,), dtype=float64, numpy=
 array([1.50249503, 2.08276659, 0.72402667, ..., 2.14044231, 2.37072222,
 

In [317]:
X_train_stack = tf.ragged.stack(stackings_X_train)
X_test_stack =  tf.ragged.stack(stackings_X_test)
X_val_stack =tf.ragged.stack(stackings_X_val)
y_train_stack = tf.ragged.stack(stackings_y_train)
y_test_stack = tf.ragged.stack(stackings_y_test)
y_val_stack = tf.ragged.stack(stackings_y_val)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [318]:
### Y VECTOR!!!!!
X_train_stack[:, :3][0][1]

<tf.Tensor: shape=(2228,), dtype=float64, numpy=
array([1129.55987093, 1829.95      , 1761.35      , ..., 1090.72360483,
        902.50562771, 1244.98333333])>

In [4]:
m = Sequential()